#!/usr/bin/env bash
set -euo pipefail

pip3 install -r requirements.txt

chmod +x \
    main-etl \
    src/extract_discourse.py \
    src/transform_discourse_to_algolia.py \
    src/load_algolia.py \
